const PLATFORMS = {
  twitter: {
    id: 'twitter',
    name: 'Twitter / X',
    icon: '𝕏',
    maxLength: 280,
    contentTypes: ['tweet', 'thread', 'reply', 'poll'],
    features: ['hashtags', 'mentions', 'emojis', 'links'],
    tones: ['casual', 'professional', 'witty', 'informative', 'provocative'],
    description: 'Short-form microblogging with 280 character limit',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: '📸',
    maxLength: 2200,
    contentTypes: ['caption', 'story', 'reel_script', 'carousel'],
    features: ['hashtags', 'emojis', 'call_to_action', 'line_breaks'],
    tones: ['aesthetic', 'casual', 'inspirational', 'storytelling', 'promotional'],
    description: 'Visual-first platform with rich captions and hashtags',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    maxLength: 3000,
    contentTypes: ['post', 'article_intro', 'thought_leadership', 'job_update'],
    features: ['hashtags', 'mentions', 'emojis', 'line_breaks', 'links'],
    tones: ['professional', 'thought_leader', 'motivational', 'educational', 'networking'],
    description: 'Professional networking with long-form content support',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: '📘',
    maxLength: 63206,
    contentTypes: ['post', 'story', 'event', 'group_post'],
    features: ['hashtags', 'emojis', 'links', 'call_to_action', 'line_breaks'],
    tones: ['casual', 'community', 'informative', 'personal', 'promotional'],
    description: 'Community-driven platform for diverse content types',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: '🎵',
    maxLength: 4000,
    contentTypes: ['video_script', 'caption', 'hook', 'trend_content'],
    features: ['hashtags', 'emojis', 'trending_sounds', 'hooks'],
    tones: ['entertaining', 'trendy', 'educational', 'relatable', 'humorous'],
    description: 'Short-form video platform focused on trends and engagement',
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: '▶️',
    maxLength: 5000,
    contentTypes: ['video_title', 'description', 'script_outline', 'shorts_script', 'community_post'],
    features: ['tags', 'timestamps', 'links', 'call_to_action', 'chapters'],
    tones: ['educational', 'entertaining', 'professional', 'casual', 'storytelling'],
    description: 'Long and short-form video with rich descriptions and SEO',
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    icon: '📌',
    maxLength: 500,
    contentTypes: ['pin_description', 'board_description', 'idea_pin'],
    features: ['keywords', 'hashtags', 'links', 'call_to_action'],
    tones: ['inspirational', 'descriptive', 'practical', 'aspirational'],
    description: 'Visual discovery platform driven by keywords and SEO',
  },
  threads: {
    id: 'threads',
    name: 'Threads',
    icon: '🧵',
    maxLength: 500,
    contentTypes: ['post', 'thread', 'reply'],
    features: ['hashtags', 'mentions', 'emojis'],
    tones: ['casual', 'conversational', 'witty', 'authentic', 'insightful'],
    description: 'Conversational text-based platform for authentic engagement',
  },
};

const UNIVERSAL_TOPICS = [
  'technology', 'business', 'marketing', 'health', 'fitness',
  'food', 'travel', 'fashion', 'education', 'finance',
  'entertainment', 'sports', 'science', 'art', 'music',
  'sustainability', 'lifestyle', 'productivity', 'motivation', 'news',
];

module.exports = { PLATFORMS, UNIVERSAL_TOPICS };
